baseurl = "https://solom.github.io/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Universal"
theme = "hugo-universal-theme"
themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "solomno"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Our services"
    identifier = "menu.services"
    url        = "/img/template-easy-customize.png"
    weight     = 3

[[menu.main]]
    name       = "Consulting"
    identifier = "section.shortcodes"
    url        = ""
    weight     = 1
    parent     = "menu.services"
    post       = 1

[[menu.main]]
    name       = "Cloud infrastructure"
    identifier = "section.headervariations"
    url        = ""
    weight     = 2
    parent     = "menu.services"
    post       = 2

[[menu.main]]
    name       = "Platform engineering"
    url        = ""
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "DevOps"
    url        = ""
    weight     = 2
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "Containers and compute"
    url        = ""
    weight     = 3
    parent     = "section.shortcodes"


[[menu.main]]
    name       = "Cloud and application Security"
    url        = ""
    weight     = 4
    parent     = "section.shortcodes"


[[menu.main]]
    name       = "Content Service Provider"
    url        = ""
    weight     = 5
    parent     = "section.headervariations"

[[menu.main]]
    name       = "Platform engineering"
    url        = ""
    weight     = 1
    parent     = "section.headervariations"

[[menu.main]]
    name       = "Platform as Code"
    url        = ""
    weight     = 1
    parent     = "section.headervariations"


[[menu.main]]
    name       = "Microsoft Azure Advisory"
    url        = ""
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = ""
    url        = ""
    weight     = 3
    parent     = "section.headervariations"

[[menu.main]]
    name       = "About us"
    identifier = "menu.about"
    url        = "/about"
    weight     = 3

[[menu.main]]
    identifier = "contact"
    name       = "Contact us"
    url        = "/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+47 98 67 96 75"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/solomno"
    pre = "<i class='fab fa-2x fa-github'></i>"


[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:post@solom.no"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    #mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Vi leverer plattform og konsulenttjenester innenfor Azure.</p>"
    copyright = "Copyright (c) 2023, Solom; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Solom"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Solom AS</strong>
        <br>Trondheim
        <strong>Norway</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +47 98 67 96 75 or post@solom.no.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+47 98 67 96 75" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:post@solom.no" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 3
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 1000
    pagination_speed = 2000

[params.services]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All services are defined in their own files. You can find example items
    # at 'exampleSite/data/services'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Vil du vite mer?"
    subtitle = "Ta kontakt på epost post@solom.no for en uforpliktende prat"
    link_url = "https://cv.solom.no/"
    link_text = "CV"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
